apiVersion: v1
kind: ReplicationController
metadata:
  name: web-controller
spec:
  replicas: 4
  selector:
    dev: wp  # Selector to manage Pods with this label
  template:
    metadata:
      labels:
        dev: wp  # Label applied to newly created Pods
    spec:
      containers:
      - name: web-container
        image: nginx:latest
