apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-exists-operator
spec:
  replicas: 7
  selector:
    matchExpressions:
    - key: env
      operator: Exists
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.26
