apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-notin-operator
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: env
      operator: NotIn
      values:
       - test
       - prod
  template:
    metadata:
      labels:
        env: wp
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
