apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: wp
    env: test
spec:
  containers:
  - name: con1
    image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: db
    env: prod
spec:
  containers:
  - name: con1
    image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: wp
    env: test
spec:
  containers:
  - name: con1
    image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: wp
    env: prod
spec:
  containers:
  - name: con1
    image: nginx:latest

